extends Node

const MAIN_MENU = "mainmenu"
const CONFIRM_QUIT = "confirmquit"
const START_GAME = "startgame"
const IN_PLAY = "inplay"
const LEAVE_PLAY = "leaveplay"
const CONFIRM_ABANDON = "confirmabandon"
const ABOUT = "about"
const TURN_MENU = "turnmenu"
const MOVE_MENU = "movemenu"
const GROUND_INVENTORY = "groundinventory"
const INVENTORY = "inventory"
const INVENTORY_DETAIL = "inventorydetail"
const EQUIPMENT = "equipment"
const EQUIPMENT_DETAIL = "equipmentdetail"
const INTERACT = "interact"
const INTERACT_EDGE = "interactedge"
const INTERACT_CORNER = "interactcorner"
